FROM drupal:8-apache

ARG DRUPAL_DATABASE_HOST
ARG DRUPAL_DATABASE_PORT
ARG DRUPAL_DATABASE_NAME
ARG DRUPAL_DATABASE_USERNAME
ARG DRUPAL_DATABASE_PASSWORD
ARG DRUPAL_HASH_SALT

ENV DRUPAL_DATABASE_HOST "$DRUPAL_DATABASE_HOST"
ENV DRUPAL_DATABASE_PORT "$DRUPAL_DATABASE_PORT"
ENV DRUPAL_DATABASE_NAME "$DRUPAL_DATABASE_NAME"
ENV DRUPAL_DATABASE_USERNAME "$DRUPAL_DATABASE_USERNAME"
ENV DRUPAL_DATABASE_PASSWORD "$DRUPAL_DATABASE_PASSWORD"
ENV DRUPAL_HASH_SALT "$DRUPAL_HASH_SALT"

ADD ./data/drupal/modules /var/www/html/modules
ADD ./data/drupal/profiles /var/www/html/profiles
ADD ./data/drupal/themes /var/www/html/themes
ADD ./data/drupal/sites /var/www/html/sites

RUN apt-get update \
    && apt-get install -y mariadb-client git \
    && rm -rf /var/lib/apt/lists/*

RUN cp /var/www/html/sites/default/default.settings.php /var/www/html/sites/default/settings.php

RUN echo " \n\
\$databases['default']['default'] = array ( \n\
  'database' => '$DRUPAL_DATABASE_NAME', \n\
  'username' => '$DRUPAL_DATABASE_USERNAME', \n\
  'password' => '$DRUPAL_DATABASE_PASSWORD', \n\
  'prefix' => '', \n\
  'host' => '$DRUPAL_DATABASE_HOST', \n\
  'port' => '$DRUPAL_DATABASE_PORT', \n\
  'namespace' => 'Drupal\\\\Core\\\\Database\\\\Driver\\\\mysql', \n\
  'driver' => 'mysql', \n\
); \n\
\$settings['hash_salt'] = '$DRUPAL_HASH_SALT'; \n\
" >> /var/www/html/sites/default/settings.php

WORKDIR "/var/www/html"

# EXPOSE 80
# CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
