
version: '3.1'
services:

  drupal:
    build:
      context: ./drupal
      dockerfile: Dockerfile.config
      args:
        - DRUPAL_DATABASE_HOST=drupal-mysql
        - DRUPAL_DATABASE_PORT=3306
        - DRUPAL_DATABASE_NAME=drupal
        - DRUPAL_DATABASE_USERNAME=drupal
        - DRUPAL_DATABASE_PASSWORD=drupal
        - DRUPAL_HASH_SALT=f3f05afc704e52cdfe8dc34ab49e447ffb437191c0376be22a
    container_name: drupal
    ports:
      - 8080:80
    volumes:
      - ./data/drupal/modules:/var/www/html/modules
      - ./data/drupal/profiles:/var/www/html/profiles
      - ./data/drupal/themes:/var/www/html/themes
      - ./data/drupal/sites:/var/www/html/sites
    environment:
      DRUPAL_DATABASE_HOST: drupal-mysql
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USERNAME: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_HASH_SALT: f3f05afc704e52cdfe8dc34ab49e447ffb437191c0376be22a
    restart: always

  mysql:
    # image: mysql:5.7
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: drupal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"
