
version: '3.3'
services:

  drupal-testing:
    stdin_open: true
    tty: true
    # image: "ricardoamaro/drupal8"
    build:
      context: ./drupal-testing
      dockerfile: Dockerfile
    container_name: drupal-testing
    ports:
      - 8080:80
    volumes:
      - ./testresults:/testresults
    # restart: always

  mysql:
    # image: mysql:5.7
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: drupal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"
